### ISSUE TITLE
Hook up Terraform

### ISSUE THREAD

**Issue by banesullivan** [ResonantGeoData/RD-OpenGeo#10]
We need to remove the Terraform CI/CD service from the ResonantGeoData repo and hook it up here

Note: we also need to remove the `watch` stuff as there will be a new `RD-WATCH` repo for that deployment

**Comment by banesullivan** [comment]
Do this post #9

**Comment by brianhelba** [comment]
Sounds good. Just ping me when #9 is ready.

**Comment by brianhelba** [comment]
> Note: we also need to remove the watch stuff as there will be a new RD-WATCH repo for that deployment

This is a little more complicated. See my comment on https://github.com/ResonantGeoData/ResonantGeoData/pull/438 :
> It will be much easier if we can keep all the TF for resources on the `RD-OpenGeo` AWS account under a single repo.  To the extent we want a DNS entry pointing to WATCH under the `resonantgeodata.com` domain, we'll need to keep that `aws_route53_record` with the rest of the TF. If we're looking for real separation, then maybe it's time for WATCH to register its own domain name.
>
> It probably will be good for WATCH to get its own SMTP server too (which the WATCH support team should be able to help with) and move out of the basement.
